.TH "spi Directory Reference" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBappenderattachable\&.h\fP"
.br
.ti -1c
.RI "file \fBfactory\&.h\fP"
.br
.ti -1c
.RI "file \fBfilter\&.h\fP"
.br
.RI "This header defines Filter and all of it's subclasses\&. "
.ti -1c
.RI "file \fBloggerfactory\&.h\fP"
.br
.ti -1c
.RI "file \fBloggerimpl\&.h\fP"
.br
.ti -1c
.RI "file \fBloggingevent\&.h\fP"
.br
.ti -1c
.RI "file \fBobjectregistry\&.h\fP"
.br
.ti -1c
.RI "file \fBrootlogger\&.h\fP"
.br
.in -1c
