.TH "impl Directory Reference" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
impl Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsyncprims\-cxx11\&.h\fP"
.br
.RI "This file contains implementations of synchronization primitives using the C++11 API\&. "
.ti -1c
.RI "file \fBsyncprims\-impl\&.h\fP"
.br
.ti -1c
.RI "file \fBsyncprims\-pmsm\&.h\fP"
.br
.RI "This file contains implementations of reader-writer locking primitive using other primitives, IOW poor man's rwlock\&. "
.ti -1c
.RI "file \fBthreads\-impl\&.h\fP"
.br
.ti -1c
.RI "file \fBtls\&.h\fP"
.br
.in -1c
