.TH "clfsappender.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clfsappender.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/appender\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::CLFSAppender\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG4CPLUS_CLFSAPPENDER_EXPORT\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef helpers::SharedObjectPtr< CLFSAppender > \fBlog4cplus::CLFSAppenderPtr\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG4CPLUS_CLFSAPPENDER_EXPORT"

.PP
Definition at line \fB55\fP of file \fBclfsappender\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
