.TH "customloglevelmanager.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
customloglevelmanager.h \- This header contains declaration internal to \fBlog4cplus\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <map>\fP
.br
\fC#include <log4cplus/thread/syncprims\&.h>\fP
.br
\fC#include <log4cplus/internal/internal\&.h>\fP
.br
\fC#include <shared_mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::internal::CustomLogLevelManager\fP"
.br
.RI "Custom log level manager used by C API\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLOG4CPLUS_PRIVATE\fP CustomLogLevelManager & \fBlog4cplus::internal::getCustomLogLevelManager\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This header contains declaration internal to \fBlog4cplus\fP\&. 

They must never be visible from user accesible headers or exported in DLL/shared library\&. 
.PP
Definition in file \fBcustomloglevelmanager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
