.TH "hierarchy.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hierarchy.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/logger\&.h>\fP
.br
\fC#include <log4cplus/thread/syncprims\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::Hierarchy\fP"
.br
.RI "This class is specialized in retrieving loggers by name and also maintaining the logger hierarchy\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLOG4CPLUS_EXPORT\fP Hierarchy & \fBlog4cplus::getDefaultHierarchy\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
