.TH "layout.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layout.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/loglevel\&.h>\fP
.br
\fC#include <log4cplus/streams\&.h>\fP
.br
\fC#include <log4cplus/tstring\&.h>\fP
.br
\fC#include <log4cplus/helpers/timehelper\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::Layout\fP"
.br
.RI "This class is used to layout strings sent to an \fC\fBlog4cplus::Appender\fP\fP\&. "
.ti -1c
.RI "class \fBlog4cplus::SimpleLayout\fP"
.br
.RI "\fBSimpleLayout\fP consists of the LogLevel of the log statement, followed by ' - ' and then the log message itself\&. "
.ti -1c
.RI "class \fBlog4cplus::TTCCLayout\fP"
.br
.RI "TTCC layout format consists of time, thread, \fBLogger\fP and nested diagnostic context information, hence the name\&. "
.ti -1c
.RI "class \fBlog4cplus::PatternLayout\fP"
.br
.RI "A flexible layout configurable with pattern string\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::pattern\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::helpers\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::spi\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLOG4CPLUS_EXPORT\fP helpers::Time const & \fBlog4cplus::getTTCCLayoutTimeBase\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
