.TH "log4cplus::thread::Semaphore" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::thread::Semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syncprims\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemaphore\fP (unsigned max, unsigned initial)"
.br
.ti -1c
.RI "\fB~Semaphore\fP ()"
.br
.ti -1c
.RI "\fBSemaphore\fP (\fBSemaphore\fP const &)=delete"
.br
.ti -1c
.RI "\fBSemaphore\fP & \fBoperator=\fP (\fBSemaphore\fP const &)=delete"
.br
.ti -1c
.RI "void \fBlock\fP () const"
.br
.ti -1c
.RI "void \fBunlock\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB102\fP of file \fBsyncprims\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::thread::Semaphore::Semaphore (unsigned max, unsigned initial)"

.SS "log4cplus::thread::Semaphore::~Semaphore ()"

.SS "log4cplus::thread::Semaphore::Semaphore (\fBSemaphore\fP const &)\fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::thread::Semaphore::lock () const"

.SS "\fBSemaphore\fP & log4cplus::thread::Semaphore::operator= (\fBSemaphore\fP const &)\fC [delete]\fP"

.SS "void log4cplus::thread::Semaphore::unlock () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
