.TH "log4cplus::exception" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::exception \- Exception class thrown by LogLog\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception\&.h>\fP
.PP
Inherits std::runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~exception\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBexception\fP \fBtstring\fP const  &\fBexception\fP \fBexception\fP const  &\fBexception\fP \fBoperator\fP =(\fBexception\fP const &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception class thrown by LogLog\&. 


.PP
\fBSee also\fP
.RS 4
\fBhelpers::LogLog\fP 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBexception\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual log4cplus::exception::~exception ()\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBexception\fP \fBtstring\fP const& \fBexception\fP \fBexception\fP const& \fBexception\fP log4cplus::exception::operator =(\fBexception\fP const &)"

.PP
Definition at line \fB49\fP of file \fBexception\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
