.TH "log4cplus::helpers::FileInfo" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::FileInfo \- \fBFileInfo\fP structure is OS independent abstraction of the \fCstat()\fP function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fileinfo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhelpers::Time\fP \fBmtime\fP"
.br
.ti -1c
.RI "bool \fBis_link\fP"
.br
.ti -1c
.RI "off_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFileInfo\fP structure is OS independent abstraction of the \fCstat()\fP function\&. 
.PP
Definition at line \fB45\fP of file \fBfileinfo\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool log4cplus::helpers::FileInfo::is_link"

.PP
Definition at line \fB48\fP of file \fBfileinfo\&.h\fP\&.
.SS "\fBhelpers::Time\fP log4cplus::helpers::FileInfo::mtime"

.PP
Definition at line \fB47\fP of file \fBfileinfo\&.h\fP\&.
.SS "off_t log4cplus::helpers::FileInfo::size"

.PP
Definition at line \fB49\fP of file \fBfileinfo\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
