.TH "log4cplus::helpers::tstring_hash" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::tstring_hash
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tstring\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBis_transparent\fP = void"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBoperator()\fP (\fBtchar\fP const *str) const noexcept"
.br
.ti -1c
.RI "std::size_t \fBoperator()\fP (\fBtstring_view\fP str) const noexcept"
.br
.ti -1c
.RI "std::size_t \fBoperator()\fP (\fBtstring\fP const &str) const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBtstring\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBlog4cplus::helpers::tstring_hash::is_transparent\fP =  void"

.PP
Definition at line \fB50\fP of file \fBtstring\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::size_t log4cplus::helpers::tstring_hash::operator() (\fBtchar\fP const * str) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB53\fP of file \fBtstring\&.h\fP\&.
.SS "std::size_t log4cplus::helpers::tstring_hash::operator() (\fBtstring\fP const & str) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB65\fP of file \fBtstring\&.h\fP\&.
.SS "std::size_t log4cplus::helpers::tstring_hash::operator() (\fBtstring_view\fP str) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB59\fP of file \fBtstring\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
