.TH "log4cplus::thread::SignalsBlocker" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::thread::SignalsBlocker \- This class blocks all POSIX signals when created and unblocks them when destroyed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignalsBlocker\fP ()"
.br
.ti -1c
.RI "\fB~SignalsBlocker\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class blocks all POSIX signals when created and unblocks them when destroyed\&. 
.PP
Definition at line \fB54\fP of file \fBthreads\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::thread::SignalsBlocker::SignalsBlocker ()"

.SS "log4cplus::thread::SignalsBlocker::~SignalsBlocker ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
