.TH "log4cplus::helpers::snprintf_buf" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::snprintf_buf
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snprintf\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsnprintf_buf\fP ()"
.br
.ti -1c
.RI "\fBtchar\fP const * \fBprint\fP (\fBtchar\fP const *fmt,\&.\&.\&.) \fBLOG4CPLUS_FORMAT_ATTRIBUTE\fP(__printf__"
.br
.ti -1c
.RI "\fBtchar\fP const int \fBprint_va_list\fP (\fBtchar\fP const *&str, \fBtchar\fP const *fmt, std::va_list) \fBLOG4CPLUS_FORMAT_ATTRIBUTE\fP(__printf__"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBsnprintf\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::helpers::snprintf_buf::snprintf_buf ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBtchar\fP const  * log4cplus::helpers::snprintf_buf::print (\fBtchar\fP const * fmt,  \&.\&.\&.)"

.SS "\fBtchar\fP const int log4cplus::helpers::snprintf_buf::print_va_list (\fBtchar\fP const *& str, \fBtchar\fP const * fmt, std::va_list)"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
