.TH "log4cplus::device_appender_detail::device_type_traits< T >" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::device_appender_detail::device_type_traits< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deviceappender\&.hxx>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T & \fBdevice_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBdevice_type\fP \fBunwrap\fP (\fBdevice_type\fP x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct log4cplus::device_appender_detail::device_type_traits< T >"
.PP
Definition at line \fB49\fP of file \fBdeviceappender\&.hxx\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T& \fBlog4cplus::device_appender_detail::device_type_traits\fP< T >::device_type"

.PP
Definition at line \fB51\fP of file \fBdeviceappender\&.hxx\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static \fBdevice_type\fP \fBlog4cplus::device_appender_detail::device_type_traits\fP< T >::unwrap (\fBdevice_type\fP x)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB55\fP of file \fBdeviceappender\&.hxx\fP\&.
.PP
Referenced by \fBlog4cplus::DeviceAppender< Device >::append()\fP, and \fBlog4cplus::DeviceAppender< Device >::close()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
