.TH "log4cplus::spi::FactoryTempl< LocalProduct, ProductFactoryBase >" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::spi::FactoryTempl< LocalProduct, ProductFactoryBase >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <factory\&.h>\fP
.PP
Inherits \fBlog4cplus::spi::LocalFactoryBase< ProductFactoryBase >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ProductFactoryBase::ProductPtr \fBProductPtr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFactoryTempl\fP (\fBtchar\fP const *n)"
.br
.ti -1c
.RI "virtual \fBProductPtr\fP \fBcreateObject\fP (\fBhelpers::Properties\fP const &props)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename LocalProduct, typename ProductFactoryBase>
.br
class log4cplus::spi::FactoryTempl< LocalProduct, ProductFactoryBase >"
.PP
Definition at line \fB232\fP of file \fBfactory\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename LocalProduct , typename ProductFactoryBase > typedef ProductFactoryBase::ProductPtr \fBlog4cplus::spi::FactoryTempl\fP< LocalProduct, ProductFactoryBase >::ProductPtr"

.PP
Definition at line \fB236\fP of file \fBfactory\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename LocalProduct , typename ProductFactoryBase > \fBlog4cplus::spi::FactoryTempl\fP< LocalProduct, ProductFactoryBase >::FactoryTempl (\fBtchar\fP const * n)\fC [inline]\fP"

.PP
Definition at line \fB238\fP of file \fBfactory\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename LocalProduct , typename ProductFactoryBase > virtual \fBProductPtr\fP \fBlog4cplus::spi::FactoryTempl\fP< LocalProduct, ProductFactoryBase >::createObject (\fBhelpers::Properties\fP const & props)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB242\fP of file \fBfactory\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
