.TH "log4cplus::device_appender_detail" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::device_appender_detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdevice_type_traits\fP"
.br
.ti -1c
.RI "struct \fBdevice_type_traits< boost::shared_ptr< T > >\fP"
.br
.ti -1c
.RI "struct \fBdevice_type_traits< std::shared_ptr< T > >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
