.TH "log4cplus::helpers::socket_closer" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::socket_closer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (SOCKET s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB93\fP of file \fBinternal/socket\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::helpers::socket_closer::operator() (SOCKET s)\fC [inline]\fP"

.PP
Definition at line \fB96\fP of file \fBinternal/socket\&.h\fP\&.
.PP
References \fBlog4cplus::helpers::INVALID_OS_SOCKET_VALUE\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
