.TH "log4cplus::helpers::LockFile" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::LockFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lockfile\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLockFile\fP (\fBtstring\fP const &lock_file, bool create_dirs=false)"
.br
.ti -1c
.RI "\fB~LockFile\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP () const"
.br
.ti -1c
.RI "void \fBunlock\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBlockfile\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::helpers::LockFile::LockFile (\fBtstring\fP const & lock_file, bool create_dirs = \fCfalse\fP)"

.SS "log4cplus::helpers::LockFile::~LockFile ()"

.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::helpers::LockFile::lock () const"

.SS "void log4cplus::helpers::LockFile::unlock () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
