.TH "log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, false >" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, false >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stringhelper\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBstep1\fP (charType *&, intType &)"
.br
.ti -1c
.RI "static constexpr bool \fBis_negative\fP (intType)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::integral intType, typename charType>
.br
struct log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, false >"
.PP
Definition at line \fB142\fP of file \fBstringhelper\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<std::integral intType, typename charType > static constexpr bool \fBlog4cplus::helpers::ConvertIntegerToStringHelper\fP< intType, charType, false >::is_negative (intType)\fC [inline]\fP, \fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB153\fP of file \fBstringhelper\&.h\fP\&.
.SS "template<std::integral intType, typename charType > static void \fBlog4cplus::helpers::ConvertIntegerToStringHelper\fP< intType, charType, false >::step1 (charType *&, intType &)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB146\fP of file \fBstringhelper\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
