.TH "log4cplus::helpers::SteadyClockGate::Info" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::SteadyClockGate::Info
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eventcounter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Info\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBcount\fP"
.br
.ti -1c
.RI "\fBDuration\fP \fBtime_span\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB67\fP of file \fBeventcounter\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::helpers::SteadyClockGate::Info::~Info ()"

.SH "Member Data Documentation"
.PP 
.SS "std::size_t log4cplus::helpers::SteadyClockGate::Info::count"

.PP
Definition at line \fB71\fP of file \fBeventcounter\&.h\fP\&.
.SS "\fBDuration\fP log4cplus::helpers::SteadyClockGate::Info::time_span"

.PP
Definition at line \fB72\fP of file \fBeventcounter\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
