.TH "log4cplus::device_appender_detail::device_type_traits< boost::shared_ptr< T > >" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::device_appender_detail::device_type_traits< boost::shared_ptr< T > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deviceappender\&.hxx>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< T > \fBdevice_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T & \fBunwrap\fP (\fBdevice_type\fP const &ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct log4cplus::device_appender_detail::device_type_traits< boost::shared_ptr< T > >"
.PP
Definition at line \fB63\fP of file \fBdeviceappender\&.hxx\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef boost::shared_ptr<T> \fBlog4cplus::device_appender_detail::device_type_traits\fP< boost::shared_ptr< T > >::device_type"

.PP
Definition at line \fB65\fP of file \fBdeviceappender\&.hxx\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static T & \fBlog4cplus::device_appender_detail::device_type_traits\fP< boost::shared_ptr< T > >::unwrap (\fBdevice_type\fP const & ptr)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB69\fP of file \fBdeviceappender\&.hxx\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
