.TH "loggingevent.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loggingevent.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <log4cplus/loglevel\&.h>\fP
.br
\fC#include <log4cplus/ndc\&.h>\fP
.br
\fC#include <log4cplus/mdc\&.h>\fP
.br
\fC#include <log4cplus/tstring\&.h>\fP
.br
\fC#include <log4cplus/helpers/timehelper\&.h>\fP
.br
\fC#include <log4cplus/thread/threads\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::spi::InternalLoggingEvent\fP"
.br
.RI "The internal representation of logging events\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::spi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
