.TH "loggerimpl.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loggerimpl.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/tstring\&.h>\fP
.br
\fC#include <log4cplus/helpers/appenderattachableimpl\&.h>\fP
.br
\fC#include <log4cplus/helpers/pointer\&.h>\fP
.br
\fC#include <log4cplus/spi/loggerfactory\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::spi::LoggerImpl\fP"
.br
.RI "This is the central class in the \fBlog4cplus\fP package\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::spi\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef LoggerImpl::SharedLoggerImplPtr \fBlog4cplus::spi::SharedLoggerImplPtr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
