.TH "pointer.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pointer.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/thread/syncprims\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <atomic>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::helpers::SharedObject\fP"
.br
.ti -1c
.RI "class \fBlog4cplus::helpers::SharedObjectPtr< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::helpers\fP"
.br
.in -1c
.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBlog4cplus::helpers::intrusive_ptr_add_ref\fP (SharedObject const *so)"
.br
.RI "Boost \fCintrusive_ptr\fP helpers\&. "
.ti -1c
.RI "void \fBlog4cplus::helpers::intrusive_ptr_release\fP (SharedObject const *so)"
.br
.in -1c
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
