.TH "syncprims-pmsm.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
syncprims-pmsm.h \- This file contains implementations of reader-writer locking primitive using other primitives, IOW poor man's rwlock\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file contains implementations of reader-writer locking primitive using other primitives, IOW poor man's rwlock\&. 

It does not contain any include guards because it is only a fragment to be included by syncprims-{pthreads,win32}\&.h\&. 
.PP
Definition in file \fBsyncprims\-pmsm\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
