.TH "syncprims-impl.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
syncprims-impl.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <log4cplus/thread/syncprims\&.h>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include <log4cplus/internal/threadsafetyanalysis\&.h>\fP
.br
\fC#include <log4cplus/thread/impl/syncprims\-cxx11\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::thread\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::thread::impl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLOG4CPLUS_EXPORT\fP void \fBlog4cplus::thread::impl::syncprims_throw_exception\fP (char const *const msg, char const *const file, int line)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
