.TH "windowsh-inc.h" 3 "Fri Sep 20 2024" "Version 3.0.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
windowsh-inc.h
.SH SYNOPSIS
.br
.PP
\fC#include <winsock2\&.h>\fP
.br
\fC#include <ws2tcpip\&.h>\fP
.br
\fC#include <windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.ti -1c
.RI "#define \fBNOGDICAPMASKS\fP"
.br
.ti -1c
.RI "#define \fBNOVIRTUALKEYCODES\fP"
.br
.ti -1c
.RI "#define \fBNOWINMESSAGES\fP"
.br
.ti -1c
.RI "#define \fBNOWINSTYLES\fP"
.br
.ti -1c
.RI "#define \fBNOSYSMETRICS\fP"
.br
.ti -1c
.RI "#define \fBNOMENUS\fP"
.br
.ti -1c
.RI "#define \fBNOICONS\fP"
.br
.ti -1c
.RI "#define \fBNOKEYSTATES\fP"
.br
.ti -1c
.RI "#define \fBNOSYSCOMMANDS\fP"
.br
.ti -1c
.RI "#define \fBNORASTEROPS\fP"
.br
.ti -1c
.RI "#define \fBNOSHOWWINDOW\fP"
.br
.ti -1c
.RI "#define \fBNOATOM\fP"
.br
.ti -1c
.RI "#define \fBNOCLIPBOARD\fP"
.br
.ti -1c
.RI "#define \fBNOCOLOR\fP"
.br
.ti -1c
.RI "#define \fBNOCTLMGR\fP"
.br
.ti -1c
.RI "#define \fBNODRAWTEXT\fP"
.br
.ti -1c
.RI "#define \fBNOGDI\fP"
.br
.ti -1c
.RI "#define \fBNOKERNEL\fP"
.br
.ti -1c
.RI "#define \fBNOUSER\fP"
.br
.ti -1c
.RI "#define \fBNONLS\fP"
.br
.ti -1c
.RI "#define \fBNOMB\fP"
.br
.ti -1c
.RI "#define \fBNOMEMMGR\fP"
.br
.ti -1c
.RI "#define \fBNOMETAFILE\fP"
.br
.ti -1c
.RI "#define \fBNOMINMAX\fP"
.br
.ti -1c
.RI "#define \fBNOMSG\fP"
.br
.ti -1c
.RI "#define \fBNOOPENFILE\fP"
.br
.ti -1c
.RI "#define \fBNOSCROLL\fP"
.br
.ti -1c
.RI "#define \fBNOSERVICE\fP"
.br
.ti -1c
.RI "#define \fBNOSOUND\fP"
.br
.ti -1c
.RI "#define \fBNOTEXTMETRIC\fP"
.br
.ti -1c
.RI "#define \fBNOWH\fP"
.br
.ti -1c
.RI "#define \fBNOWINOFFSETS\fP"
.br
.ti -1c
.RI "#define \fBNOCOMM\fP"
.br
.ti -1c
.RI "#define \fBNOKANJI\fP"
.br
.ti -1c
.RI "#define \fBNOHELP\fP"
.br
.ti -1c
.RI "#define \fBNOPROFILER\fP"
.br
.ti -1c
.RI "#define \fBNODEFERWINDOWPOS\fP"
.br
.ti -1c
.RI "#define \fBNOMCX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOATOM"

.PP
Definition at line \fB71\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOCLIPBOARD"

.PP
Definition at line \fB74\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOCOLOR"

.PP
Definition at line \fB77\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOCOMM"

.PP
Definition at line \fB134\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOCTLMGR"

.PP
Definition at line \fB80\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NODEFERWINDOWPOS"

.PP
Definition at line \fB146\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NODRAWTEXT"

.PP
Definition at line \fB83\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOGDI"

.PP
Definition at line \fB86\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOGDICAPMASKS"

.PP
Definition at line \fB38\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOHELP"

.PP
Definition at line \fB140\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOICONS"

.PP
Definition at line \fB56\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOKANJI"

.PP
Definition at line \fB137\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOKERNEL"

.PP
Definition at line \fB89\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOKEYSTATES"

.PP
Definition at line \fB59\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMB"

.PP
Definition at line \fB98\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMCX"

.PP
Definition at line \fB149\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMEMMGR"

.PP
Definition at line \fB101\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMENUS"

.PP
Definition at line \fB53\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMETAFILE"

.PP
Definition at line \fB104\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMINMAX"

.PP
Definition at line \fB107\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOMSG"

.PP
Definition at line \fB110\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NONLS"

.PP
Definition at line \fB95\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOOPENFILE"

.PP
Definition at line \fB113\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOPROFILER"

.PP
Definition at line \fB143\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NORASTEROPS"

.PP
Definition at line \fB65\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSCROLL"

.PP
Definition at line \fB116\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSERVICE"

.PP
Definition at line \fB119\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSHOWWINDOW"

.PP
Definition at line \fB68\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSOUND"

.PP
Definition at line \fB122\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSYSCOMMANDS"

.PP
Definition at line \fB62\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOSYSMETRICS"

.PP
Definition at line \fB50\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOTEXTMETRIC"

.PP
Definition at line \fB125\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOUSER"

.PP
Definition at line \fB92\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOVIRTUALKEYCODES"

.PP
Definition at line \fB41\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOWH"

.PP
Definition at line \fB128\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOWINMESSAGES"

.PP
Definition at line \fB44\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOWINOFFSETS"

.PP
Definition at line \fB131\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define NOWINSTYLES"

.PP
Definition at line \fB47\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SS "#define WIN32_LEAN_AND_MEAN"

.PP
Definition at line \fB35\fP of file \fBwindowsh\-inc\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
