.TH "log4cplus Directory Reference" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBboost\fP"
.br
.ti -1c
.RI "directory \fBconfig\fP"
.br
.ti -1c
.RI "directory \fBhelpers\fP"
.br
.ti -1c
.RI "directory \fBinternal\fP"
.br
.ti -1c
.RI "directory \fBspi\fP"
.br
.ti -1c
.RI "directory \fBthread\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBappender\&.h\fP"
.br
.ti -1c
.RI "file \fBasyncappender\&.h\fP"
.br
.ti -1c
.RI "file \fBcallbackappender\&.h\fP"
.br
.ti -1c
.RI "file \fBclfsappender\&.h\fP"
.br
.ti -1c
.RI "file \fBclogger\&.h\fP"
.br
.RI "Module: Log4CPLUS File: \fBclogger\&.h\fP Created: 01/2011 Author: Jens Rehsack\&. "
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBconfig\&.hxx\fP"
.br
.ti -1c
.RI "file \fBconfigurator\&.h\fP"
.br
.ti -1c
.RI "file \fBconsoleappender\&.h\fP"
.br
.ti -1c
.RI "file \fBexception\&.h\fP"
.br
.ti -1c
.RI "file \fBfileappender\&.h\fP"
.br
.ti -1c
.RI "file \fBfstreams\&.h\fP"
.br
.ti -1c
.RI "file \fBhierarchy\&.h\fP"
.br
.ti -1c
.RI "file \fBhierarchylocker\&.h\fP"
.br
.ti -1c
.RI "file \fBinitializer\&.h\fP"
.br
.ti -1c
.RI "file \fBlayout\&.h\fP"
.br
.ti -1c
.RI "file \fBlog4cplus\&.h\fP"
.br
.ti -1c
.RI "file \fBlog4judpappender\&.h\fP"
.br
.ti -1c
.RI "file \fBlogger\&.h\fP"
.br
.RI "This header defines the Logger class and the logging macros\&. "
.ti -1c
.RI "file \fBloggingmacros\&.h\fP"
.br
.RI "This header defines the logging macros\&. "
.ti -1c
.RI "file \fBloglevel\&.h\fP"
.br
.RI "This header defines the LogLevel type\&. "
.ti -1c
.RI "file \fBmdc\&.h\fP"
.br
.ti -1c
.RI "file \fBmsttsappender\&.h\fP"
.br
.ti -1c
.RI "file \fBndc\&.h\fP"
.br
.RI "This header defined the NDC class\&. "
.ti -1c
.RI "file \fBnteventlogappender\&.h\fP"
.br
.ti -1c
.RI "file \fBnullappender\&.h\fP"
.br
.ti -1c
.RI "file \fBqt4debugappender\&.h\fP"
.br
.ti -1c
.RI "file \fBqt5debugappender\&.h\fP"
.br
.ti -1c
.RI "file \fBsocketappender\&.h\fP"
.br
.ti -1c
.RI "file \fBstreams\&.h\fP"
.br
.ti -1c
.RI "file \fBsyslogappender\&.h\fP"
.br
.ti -1c
.RI "file \fBtchar\&.h\fP"
.br
.ti -1c
.RI "file \fBtracelogger\&.h\fP"
.br
.ti -1c
.RI "file \fBtstring\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.ti -1c
.RI "file \fBwin32consoleappender\&.h\fP"
.br
.ti -1c
.RI "file \fBwin32debugappender\&.h\fP"
.br
.in -1c
