.TH "internal Directory Reference" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcustomloglevelmanager\&.h\fP"
.br
.RI "This header contains declaration internal to \fBlog4cplus\fP\&. "
.ti -1c
.RI "file \fBcygwin\-win32\&.h\fP"
.br
.ti -1c
.RI "file \fBenv\&.h\fP"
.br
.ti -1c
.RI "file \fBinternal\&.h\fP"
.br
.RI "This header contains declaration internal to \fBlog4cplus\fP\&. "
.ti -1c
.RI "file \fBinternal/socket\&.h\fP"
.br
.RI "This header contains declaration internal to \fBlog4cplus\fP\&. "
.in -1c
