.TH "asyncappender.h" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asyncappender.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/helpers/queue\&.h>\fP
.br
\fC#include <log4cplus/appender\&.h>\fP
.br
\fC#include <log4cplus/thread/threads\&.h>\fP
.br
\fC#include <log4cplus/helpers/appenderattachableimpl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::AsyncAppender\fP"
.br
.RI "This \fC\fBAppender\fP\fP is a wrapper to which other appenders can be attached\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef helpers::SharedObjectPtr< AsyncAppender > \fBlog4cplus::AsyncAppenderPtr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
