.TH "log4cplus::thread::Mutex" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::thread::Mutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syncprims\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "\fB~Mutex\fP ()"
.br
.ti -1c
.RI "\fBMutex\fP (\fBMutex\fP const &)=delete"
.br
.ti -1c
.RI "\fBMutex\fP & \fBoperator=\fP (\fBMutex\fP const &)=delete"
.br
.ti -1c
.RI "void \fBlock\fP () const"
.br
.ti -1c
.RI "void \fBunlock\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fBsyncprims\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::thread::Mutex::Mutex ()"

.SS "log4cplus::thread::Mutex::~Mutex ()"

.SS "log4cplus::thread::Mutex::Mutex (\fBMutex\fP const &)\fC [delete]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::thread::Mutex::lock () const"

.SS "\fBMutex\fP & log4cplus::thread::Mutex::operator= (\fBMutex\fP const &)\fC [delete]\fP"

.SS "void log4cplus::thread::Mutex::unlock () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
