.TH "log4cplus.h" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/version\&.h>\fP
.br
\fC#include <log4cplus/loglevel\&.h>\fP
.br
\fC#include <log4cplus/logger\&.h>\fP
.br
\fC#include <log4cplus/layout\&.h>\fP
.br
\fC#include <log4cplus/hierarchy\&.h>\fP
.br
\fC#include <log4cplus/loggingmacros\&.h>\fP
.br
\fC#include <log4cplus/tracelogger\&.h>\fP
.br
\fC#include <log4cplus/configurator\&.h>\fP
.br
\fC#include <log4cplus/appender\&.h>\fP
.br
\fC#include <log4cplus/mdc\&.h>\fP
.br
\fC#include <log4cplus/ndc\&.h>\fP
.br
\fC#include <log4cplus/initializer\&.h>\fP
.br
\fC#include <log4cplus/helpers/property\&.h>\fP
.br
\fC#include <log4cplus/spi/factory\&.h>\fP
.br
\fC#include <log4cplus/spi/filter\&.h>\fP
.br
\fC#include <log4cplus/spi/loggingevent\&.h>\fP
.br
\fC#include <log4cplus/asyncappender\&.h>\fP
.br
\fC#include <log4cplus/consoleappender\&.h>\fP
.br
\fC#include <log4cplus/fileappender\&.h>\fP
.br
\fC#include <log4cplus/socketappender\&.h>\fP
.br
\fC#include <log4cplus/syslogappender\&.h>\fP
.br
\fC#include <log4cplus/nullappender\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
