.TH "log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, true >" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stringhelper\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBstep1\fP (charType *&it, intType &value)"
.br
.ti -1c
.RI "static bool \fBis_negative\fP (intType val)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename intType, typename charType>
.br
struct log4cplus::helpers::ConvertIntegerToStringHelper< intType, charType, true >"
.PP
Definition at line \fB103\fP of file \fBstringhelper\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename intType , typename charType > static bool \fBlog4cplus::helpers::ConvertIntegerToStringHelper\fP< intType, charType, true >::is_negative (intType val)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB134\fP of file \fBstringhelper\&.h\fP\&.
.SS "template<typename intType , typename charType > static void \fBlog4cplus::helpers::ConvertIntegerToStringHelper\fP< intType, charType, true >::step1 (charType *& it, intType & value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB107\fP of file \fBstringhelper\&.h\fP\&.
.PP
References \fBLOG4CPLUS_TEXT\fP, and \fBLOG4CPLUS_UNLIKELY\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
