.TH "log4cplus::ConfigureAndWatchThread" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::ConfigureAndWatchThread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configurator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigureAndWatchThread\fP (const \fBlog4cplus::tstring\fP &propertyFile, unsigned int millis=60 *1000)"
.br
.ti -1c
.RI "virtual \fB~ConfigureAndWatchThread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB360\fP of file \fBconfigurator\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::ConfigureAndWatchThread::ConfigureAndWatchThread (const \fBlog4cplus::tstring\fP & propertyFile, unsigned int millis = \fC60 *1000\fP)"

.SS "virtual log4cplus::ConfigureAndWatchThread::~ConfigureAndWatchThread ()\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
