.TH "log4cplus::internal::gft_scratch_pad" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::internal::gft_scratch_pad
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgft_scratch_pad\fP ()"
.br
.ti -1c
.RI "\fB~gft_scratch_pad\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBq_str\fP"
.br
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBuc_q_str\fP"
.br
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBs_str\fP"
.br
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBret\fP"
.br
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBfmt\fP"
.br
.ti -1c
.RI "\fBlog4cplus::tstring\fP \fBtmp\fP"
.br
.ti -1c
.RI "std::vector< \fBtchar\fP > \fBbuffer\fP"
.br
.ti -1c
.RI "bool \fBuc_q_str_valid\fP"
.br
.ti -1c
.RI "bool \fBq_str_valid\fP"
.br
.ti -1c
.RI "bool \fBs_str_valid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB73\fP of file \fBinternal\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::internal::gft_scratch_pad::gft_scratch_pad ()"

.SS "log4cplus::internal::gft_scratch_pad::~gft_scratch_pad ()"

.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::internal::gft_scratch_pad::reset ()\fC [inline]\fP"

.PP
Definition at line \fB79\fP of file \fBinternal\&.h\fP\&.
.PP
References \fBq_str_valid\fP, \fBret\fP, \fBs_str_valid\fP, and \fBuc_q_str_valid\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBtchar\fP> log4cplus::internal::gft_scratch_pad::buffer"

.PP
Definition at line \fB93\fP of file \fBinternal\&.h\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::fmt"

.PP
Definition at line \fB91\fP of file \fBinternal\&.h\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::q_str"

.PP
Definition at line \fB87\fP of file \fBinternal\&.h\fP\&.
.SS "bool log4cplus::internal::gft_scratch_pad::q_str_valid"

.PP
Definition at line \fB95\fP of file \fBinternal\&.h\fP\&.
.PP
Referenced by \fBreset()\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::ret"

.PP
Definition at line \fB90\fP of file \fBinternal\&.h\fP\&.
.PP
Referenced by \fBreset()\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::s_str"

.PP
Definition at line \fB89\fP of file \fBinternal\&.h\fP\&.
.SS "bool log4cplus::internal::gft_scratch_pad::s_str_valid"

.PP
Definition at line \fB96\fP of file \fBinternal\&.h\fP\&.
.PP
Referenced by \fBreset()\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::tmp"

.PP
Definition at line \fB92\fP of file \fBinternal\&.h\fP\&.
.SS "\fBlog4cplus::tstring\fP log4cplus::internal::gft_scratch_pad::uc_q_str"

.PP
Definition at line \fB88\fP of file \fBinternal\&.h\fP\&.
.SS "bool log4cplus::internal::gft_scratch_pad::uc_q_str_valid"

.PP
Definition at line \fB94\fP of file \fBinternal\&.h\fP\&.
.PP
Referenced by \fBreset()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
