.TH "log4cplus::OnlyOnceErrorHandler" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::OnlyOnceErrorHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <appender\&.h>\fP
.PP
Inherits \fBlog4cplus::ErrorHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnlyOnceErrorHandler\fP ()"
.br
.ti -1c
.RI "virtual \fB~OnlyOnceErrorHandler\fP ()"
.br
.ti -1c
.RI "virtual void \fBerror\fP (const \fBlog4cplus::tstring\fP &err)"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBappender\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::OnlyOnceErrorHandler::OnlyOnceErrorHandler ()"

.SS "virtual log4cplus::OnlyOnceErrorHandler::~OnlyOnceErrorHandler ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void log4cplus::OnlyOnceErrorHandler::error (const \fBlog4cplus::tstring\fP & err)\fC [virtual]\fP"

.PP
Implements \fBlog4cplus::ErrorHandler\fP\&.
.SS "virtual void log4cplus::OnlyOnceErrorHandler::reset ()\fC [virtual]\fP"

.PP
Implements \fBlog4cplus::ErrorHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
