.TH "log4cplus::thread::impl::SharedMutex" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::thread::impl::SharedMutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syncprims\-impl\&.h>\fP
.PP
Inherits \fBlog4cplus::thread::SharedMutexImplBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedMutex\fP ()"
.br
.ti -1c
.RI "\fB~SharedMutex\fP ()"
.br
.ti -1c
.RI "void \fBrdlock\fP () const"
.br
.ti -1c
.RI "void \fBwrlock\fP () const"
.br
.ti -1c
.RI "void \fBrdunlock\fP () const"
.br
.ti -1c
.RI "void \fBwrunlock\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBsyncprims\-impl\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::thread::impl::SharedMutex::SharedMutex ()"

.SS "log4cplus::thread::impl::SharedMutex::~SharedMutex ()"

.SH "Member Function Documentation"
.PP 
.SS "void log4cplus::thread::impl::SharedMutex::rdlock () const"

.SS "void log4cplus::thread::impl::SharedMutex::rdunlock () const"

.SS "void log4cplus::thread::impl::SharedMutex::wrlock () const"

.SS "void log4cplus::thread::impl::SharedMutex::wrunlock () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
