.TH "log4cplus::thread::SharedMutex" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::thread::SharedMutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <syncprims\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedMutex\fP ()"
.br
.ti -1c
.RI "\fB~SharedMutex\fP ()"
.br
.ti -1c
.RI "void \fBrdlock\fP () const"
.br
.ti -1c
.RI "void \fBrdunlock\fP () const"
.br
.ti -1c
.RI "void \fBwrlock\fP () const"
.br
.ti -1c
.RI "void \fBwrunlock\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB157\fP of file \fBsyncprims\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SharedMutex::SharedMutex ()\fC [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBsyncprims\-pmsm\&.h\fP\&.
.SS "SharedMutex::~SharedMutex ()\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBsyncprims\-pmsm\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SharedMutex::rdlock () const\fC [inline]\fP"

.PP
Definition at line \fB61\fP of file \fBsyncprims\-pmsm\&.h\fP\&.
.SS "void SharedMutex::rdunlock () const\fC [inline]\fP"

.PP
Definition at line \fB75\fP of file \fBsyncprims\-pmsm\&.h\fP\&.
.SS "void SharedMutex::wrlock () const\fC [inline]\fP"

.PP
Definition at line \fB87\fP of file \fBsyncprims\-pmsm\&.h\fP\&.
.SS "void SharedMutex::wrunlock () const\fC [inline]\fP"

.PP
Definition at line \fB111\fP of file \fBsyncprims\-pmsm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
