.TH "log4cplus::internal::appender_sratch_pad" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::internal::appender_sratch_pad
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBappender_sratch_pad\fP ()"
.br
.ti -1c
.RI "\fB~appender_sratch_pad\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtostringstream\fP \fBoss\fP"
.br
.ti -1c
.RI "\fBtstring\fP \fBstr\fP"
.br
.ti -1c
.RI "std::string \fBchstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB100\fP of file \fBinternal\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::internal::appender_sratch_pad::appender_sratch_pad ()"

.SS "log4cplus::internal::appender_sratch_pad::~appender_sratch_pad ()"

.SH "Member Data Documentation"
.PP 
.SS "std::string log4cplus::internal::appender_sratch_pad::chstr"

.PP
Definition at line \fB107\fP of file \fBinternal\&.h\fP\&.
.SS "\fBtostringstream\fP log4cplus::internal::appender_sratch_pad::oss"

.PP
Definition at line \fB105\fP of file \fBinternal\&.h\fP\&.
.SS "\fBtstring\fP log4cplus::internal::appender_sratch_pad::str"

.PP
Definition at line \fB106\fP of file \fBinternal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
