.TH "log4cplus::NullAppender" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4cplus::NullAppender \- Appends log events to a file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nullappender\&.h>\fP
.PP
Inherits \fBlog4cplus::Appender\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullAppender\fP ()"
.br
.ti -1c
.RI "\fBNullAppender\fP (const \fBlog4cplus::helpers::Properties\fP &)"
.br
.ti -1c
.RI "virtual \fB~NullAppender\fP ()"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.RI "Release any resources allocated within the appender such as file handles, network connections, etc\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBappend\fP (const \fBlog4cplus::spi::InternalLoggingEvent\fP &event)"
.br
.RI "Subclasses of \fC\fBAppender\fP\fP should implement this method to perform actual logging\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Appends log events to a file\&. 
.PP
Definition at line \fB41\fP of file \fBnullappender\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4cplus::NullAppender::NullAppender ()"

.SS "log4cplus::NullAppender::NullAppender (const \fBlog4cplus::helpers::Properties\fP &)"

.SS "virtual log4cplus::NullAppender::~NullAppender ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void log4cplus::NullAppender::append (const \fBlog4cplus::spi::InternalLoggingEvent\fP & event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Subclasses of \fC\fBAppender\fP\fP should implement this method to perform actual logging\&. 
.PP
\fBSee also\fP
.RS 4
\fBdoAppend\fP method\&. 
.RE
.PP

.PP
Implements \fBlog4cplus::Appender\fP\&.
.SS "virtual void log4cplus::NullAppender::close ()\fC [virtual]\fP"

.PP
Release any resources allocated within the appender such as file handles, network connections, etc\&. It is a programming error to append to a closed appender\&. 
.PP
Implements \fBlog4cplus::Appender\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
