.TH "msttsappender.h" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msttsappender.h
.SH SYNOPSIS
.br
.PP
\fC#include <log4cplus/config\&.hxx>\fP
.br
\fC#include <log4cplus/appender\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlog4cplus::MSTTSAppender\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG4CPLUS_MSTTSAPPENDER_EXPORT\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef helpers::SharedObjectPtr< MSTTSAppender > \fBlog4cplus::MSTTSAppenderPtr\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG4CPLUS_MSTTSAPPENDER_EXPORT"

.PP
Definition at line \fB62\fP of file \fBmsttsappender\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
