.TH "syncprims-cxx11.h" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
syncprims-cxx11.h \- This file contains implementations of synchronization primitives using the C++11 API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'log4cplus/thread/impl/syncprims\-pmsm\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlog4cplus\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::thread\fP"
.br
.ti -1c
.RI "namespace \fBlog4cplus::thread::impl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains implementations of synchronization primitives using the C++11 API\&. 

It does not contain any include guards because it is only a fragment to be included by \fBsyncprims\&.h\fP\&. 
.PP
Definition in file \fBsyncprims\-cxx11\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
