.TH "win32.h" 3 "Fri Sep 20 2024" "Version 2.1.0" "log4cplus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
win32.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_TIME_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_SYS_TIMEB_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_FTIME\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_USE_WINSOCK\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_OUTPUTDEBUGSTRING\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_WIN32_CONSOLE\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_SYS_TYPES_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_SYS_LOCKING_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_FCNTL_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_IO_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_STDIO_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_WCHAR_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_STDARG_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_STDLIB_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_ERRNO_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_SYS_STAT_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_TIME_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_STDLIB_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_DIRECT_H\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_VSNPRINTF\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE__VSNPRINTF\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE__VSNWPRINTF\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE__TSOPEN\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_DLLMAIN_HINSTANCE\fP   HINSTANCE"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_HAVE_NT_EVENT_LOG\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_STATIC\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_EXPORT\fP"
.br
.ti -1c
.RI "#define \fBLOG4CPLUS_USE_WIN32_THREADS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG4CPLUS_DLLMAIN_HINSTANCE   HINSTANCE"

.PP
Definition at line \fB113\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_EXPORT"

.PP
Definition at line \fB141\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE__TSOPEN"

.PP
Definition at line \fB111\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE__VSNPRINTF"

.PP
Definition at line \fB75\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE__VSNWPRINTF"

.PP
Definition at line \fB76\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_DIRECT_H"

.PP
Definition at line \fB71\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_ERRNO_H"

.PP
Definition at line \fB67\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_FCNTL_H"

.PP
Definition at line \fB61\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_FTIME"

.PP
Definition at line \fB45\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_IO_H"

.PP
Definition at line \fB62\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_NT_EVENT_LOG"

.PP
Definition at line \fB114\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_OUTPUTDEBUGSTRING"

.PP
Definition at line \fB54\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_STDARG_H"

.PP
Definition at line \fB65\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_STDIO_H"

.PP
Definition at line \fB63\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_STDLIB_H"

.PP
Definition at line \fB70\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_STDLIB_H"

.PP
Definition at line \fB70\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_SYS_LOCKING_H"

.PP
Definition at line \fB60\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_SYS_STAT_H"

.PP
Definition at line \fB68\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_SYS_TIMEB_H"

.PP
Definition at line \fB44\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_SYS_TYPES_H"

.PP
Definition at line \fB59\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_TIME_H"

.PP
Definition at line \fB69\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_TIME_H"

.PP
Definition at line \fB69\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_VSNPRINTF"

.PP
Definition at line \fB74\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_WCHAR_H"

.PP
Definition at line \fB64\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_HAVE_WIN32_CONSOLE"

.PP
Definition at line \fB57\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_STATIC"

.PP
Definition at line \fB127\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_USE_WIN32_THREADS"

.PP
Definition at line \fB145\fP of file \fBwin32\&.h\fP\&.
.SS "#define LOG4CPLUS_USE_WINSOCK"

.PP
Definition at line \fB51\fP of file \fBwin32\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for log4cplus from the source code\&.
