log4cplus::TraceLogger Class Reference
This class is used to produce `Trace` logging.
#include <tracelogger.h>
Public Member Functions
TraceLogger (Logger l, log4cplus::tstring _msg, log4cplus::helpers::SourceLocation _location=log4cplus::helpers::SourceLocation::current())
TraceLogger (Logger l, log4cplus::tstring _msg, const char *_file, int _line, char const *_function)
~TraceLogger ()
TraceLogger (TraceLogger const &)=delete
TraceLogger (TraceLogger &&)=delete
TraceLogger & operator= (TraceLogger const &)=delete
TraceLogger & operator= (TraceLogger &&)=delete
Detailed Description
This class is used to produce `Trace` logging.
When an instance of this class is created, it will log a `ENTER: ` + msg log message if TRACE_LOG_LEVEL is enabled for logger. When an instance of this class is destroyed, it will log a `ENTER: ` + msg log message if TRACE_LOG_LEVEL is enabled for logger.
See also
LOG4CPLUS_TRACE
Definition at line 51 of file tracelogger.h.
Constructor & Destructor Documentation
TraceLogger() [1/4]
log4cplus::TraceLogger::TraceLogger (Logger l, log4cplus::tstring _msg, log4cplus::helpers::SourceLocation _location = log4cplus::helpers::SourceLocation::current ()) [inline]
Definition at line 54 of file tracelogger.h.
References log4cplus::Logger::forcedLog(), log4cplus::Logger::isEnabledFor(), LOG4CPLUS_TEXT, and log4cplus::TRACE_LOG_LEVEL.
TraceLogger() [2/4]
log4cplus::TraceLogger::TraceLogger (Logger l, log4cplus::tstring _msg, const char * _file, int _line, char const * _function) [inline]
Definition at line 65 of file tracelogger.h.
References log4cplus::Logger::forcedLog(), log4cplus::Logger::isEnabledFor(), LOG4CPLUS_TEXT, and log4cplus::TRACE_LOG_LEVEL.
 TraceLogger()
log4cplus::TraceLogger::~TraceLogger () [inline]
Definition at line 75 of file tracelogger.h.
References log4cplus::Logger::forcedLog(), log4cplus::Logger::isEnabledFor(), LOG4CPLUS_TEXT, and log4cplus::TRACE_LOG_LEVEL.
TraceLogger() [3/4]
log4cplus::TraceLogger::TraceLogger (TraceLogger const &) [delete]
TraceLogger() [4/4]
log4cplus::TraceLogger::TraceLogger (TraceLogger &&) [delete]
Member Function Documentation
operator=() [1/2]
TraceLogger & log4cplus::TraceLogger::operator= (TraceLogger &&) [delete]
operator=() [2/2]
TraceLogger & log4cplus::TraceLogger::operator= (TraceLogger const &) [delete]
The documentation for this class was generated from the following file:
tracelogger.h