log4cplus::DeviceAppender< Device > Class Template Reference
This appender wraps Boost IOStreams' Device concept instance as underlying sink for the appender.
#include <deviceappender.hxx>
Public Types
typedef device_appender_detail::device_type_traits< Device > device_traits
typedef device_traits::device_type device_type
Public Member Functions
template<typename D >
DeviceAppender (D &d, bool close_device=true)
template<typename D >
DeviceAppender (boost::shared_ptr< D > const &d, bool close_device=true)
template<typename D >
DeviceAppender (std::shared_ptr< D > const &d, bool close_device=true)
template<typename D >
DeviceAppender (D &d, const helpers::Properties &props)
template<typename D >
DeviceAppender (boost::shared_ptr< D > const &d, const helpers::Properties &props)
template<typename D >
DeviceAppender (std::shared_ptr< D > const &d, const helpers::Properties &props)
DeviceAppender (DeviceAppender const &)=delete
DeviceAppender & operator= (DeviceAppender const &)=delete
virtual ~DeviceAppender ()
virtual void close () override
Release any resources allocated within the appender such as file handles, network connections, etc.
Protected Member Functions
virtual void append (log4cplus::spi::InternalLoggingEvent const &event) override
Subclasses of Appender should implement this method to perform actual logging.
Protected Attributes
device_type device
bool close_flag
Additional Inherited Members
Detailed Description
template<typename Device>
class log4cplus::DeviceAppender< Device >
This appender wraps Boost IOStreams' Device concept instance as underlying sink for the appender.
Template Parameters
Device Boost IOStreams' Device concept instance
Definition at line 100 of file deviceappender.hxx.
Member Typedef Documentation
device_traits
template<typename Device >
typedef device_appender_detail::device_type_traits<Device> log4cplus::DeviceAppender< Device >::device_traits
Definition at line 104 of file deviceappender.hxx.
device_type
template<typename Device >
typedef device_traits::device_type log4cplus::DeviceAppender< Device >::device_type
Definition at line 105 of file deviceappender.hxx.
Constructor & Destructor Documentation
DeviceAppender() [1/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (D & d, bool close_device = true) [inline]
Definition at line 108 of file deviceappender.hxx.
DeviceAppender() [2/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (boost::shared_ptr< D > const & d, bool close_device = true) [inline]
Definition at line 114 of file deviceappender.hxx.
DeviceAppender() [3/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (std::shared_ptr< D > const & d, bool close_device = true) [inline]
Definition at line 120 of file deviceappender.hxx.
DeviceAppender() [4/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (D & d, const helpers::Properties & props) [inline]
Definition at line 126 of file deviceappender.hxx.
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::helpers::Properties::getBool(), and LOG4CPLUS_TEXT.
DeviceAppender() [5/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (boost::shared_ptr< D > const & d, const helpers::Properties & props) [inline]
Definition at line 135 of file deviceappender.hxx.
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::helpers::Properties::getBool(), and LOG4CPLUS_TEXT.
DeviceAppender() [6/7]
template<typename Device >
template<typename D >
log4cplus::DeviceAppender< Device >::DeviceAppender (std::shared_ptr< D > const & d, const helpers::Properties & props) [inline]
Definition at line 145 of file deviceappender.hxx.
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::helpers::Properties::getBool(), and LOG4CPLUS_TEXT.
DeviceAppender() [7/7]
template<typename Device >
log4cplus::DeviceAppender< Device >::DeviceAppender (DeviceAppender< Device > const &) [delete]
 DeviceAppender()
template<typename Device >
virtual log4cplus::DeviceAppender< Device >::~DeviceAppender () [inline], [virtual]
Definition at line 158 of file deviceappender.hxx.
References log4cplus::Appender::destructorImpl().
Member Function Documentation
append()
template<typename Device >
virtual void log4cplus::DeviceAppender< Device >::append (log4cplus::spi::InternalLoggingEvent const & event) [inline], [override], [protected], [virtual]
Subclasses of Appender should implement this method to perform actual logging.
See also
doAppend method.
Implements log4cplus::Appender.
Definition at line 174 of file deviceappender.hxx.
References log4cplus::DeviceAppender< Device >::device, log4cplus::Appender::formatEvent(), log4cplus::device_appender_detail::device_type_traits< T >::unwrap(), and log4cplus::helpers::write().
close()
template<typename Device >
virtual void log4cplus::DeviceAppender< Device >::close () [inline], [override], [virtual]
Release any resources allocated within the appender such as file handles, network connections, etc.
It is a programming error to append to a closed appender.
Implements log4cplus::Appender.
Definition at line 165 of file deviceappender.hxx.
References log4cplus::DeviceAppender< Device >::close_flag, log4cplus::DeviceAppender< Device >::device, and log4cplus::device_appender_detail::device_type_traits< T >::unwrap().
operator=()
template<typename Device >
DeviceAppender & log4cplus::DeviceAppender< Device >::operator= (DeviceAppender< Device > const &) [delete]
Member Data Documentation
close_flag
template<typename Device >
bool log4cplus::DeviceAppender< Device >::close_flag [protected]
Definition at line 182 of file deviceappender.hxx.
Referenced by log4cplus::DeviceAppender< Device >::close(), and log4cplus::DeviceAppender< Device >::DeviceAppender().
device
template<typename Device >
device_type log4cplus::DeviceAppender< Device >::device [protected]
Definition at line 181 of file deviceappender.hxx.
Referenced by log4cplus::DeviceAppender< Device >::append(), and log4cplus::DeviceAppender< Device >::close().
The documentation for this class was generated from the following file:
deviceappender.hxx